[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:streamlit]
command=streamlit run app.py --server.port=8502 --server.address=127.0.0.1 --server.enableCORS=false --server.enableXsrfProtection=false --server.headless=true --browser.gatherUsageStats=false --server.fileWatcherType=none --server.enableWebsocketCompression=false
directory=/app
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:mlflow]
command=mlflow server --host 127.0.0.1 --port 5000 --workers 1 --static-prefix /mlflow --backend-store-uri sqlite:////app/data/mlflow/mlflow.db --default-artifact-root /app/data/mlflow/artifacts
directory=/app
autostart=true
autorestart=true
priority=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:prometheus]
command=prometheus --config.file=/etc/prometheus/prometheus.yml --web.route-prefix=/prometheus --web.external-url=http://localhost:8501/prometheus/ --storage.tsdb.path=/tmp/prometheus --storage.tsdb.retention.time=2h --storage.tsdb.wal-compression
autostart=true
autorestart=true
priority=40
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:grafana]
command=/usr/sbin/grafana-server --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini
autostart=true
autorestart=true
priority=50
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
